# Generated by Django 4.1.1 on 2022-09-17 10:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0006_alter_subject_enroll_alter_subject_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='credit',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(0)]),
        ),
    ]
